// <auto-generated />
namespace US07.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewTableMembres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTableMembres));
        
        string IMigrationMetadata.Id
        {
            get { return "202107112058296_NewTableMembres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
